### ISSUE TITLE
Change Twitter Username

### ISSUE THREAD

**Issue by enzanki-ars** [DarbyComputerClub/DarbyComputerClub.github.io#3]
Twitter user name is not consitant with the site. If Slack is changed, then I will change the Twitter username.

**Comment by jacobsims** [comment]
Slack has been changed.

You will also have to update the Twitter embed (which is not based only on username).

**Comment by enzanki-ars** [comment]
Based on my memory, the embed should not change. You should definitely warn everyone in slack/out of slack. No more username changes.

**Comment by enzanki-ars** [comment]
Twitter changed to DarbyCompClub. It seems that Twitter usernames are restricted to 15 characters.

**Comment by enzanki-ars** [comment]
By the way, the embed has not changed. The embed code has to be created I the account settings tab, which creates a code that is linked to the account.

**Comment by enzanki-ars** [comment]
The headers need to be changed. They link to a username that is impossible.

**Comment by jacobsims** [comment]
Fixed by commit c408d4b1c7a331ba0782362a9dc777092de49a45
